import { MOCK_AGENT_ID } from '@/lib/constants';

export const initialProperties = [
  {
    agentId: MOCK_AGENT_ID,
    title: 'Spacious Downtown Apartment',
    price: 750000,
    address: '123 Main St, Anytown, USA',
    bedrooms: 2,
    bathrooms: 2,
    description: 'Modern apartment with city views, close to all amenities.',
    status: 'active',
    imageUrl: '/downtown-apartment.png',
    sqft: 1200,
    propertyType: 'Apartment',
  },
  {
    agentId: MOCK_AGENT_ID,
    title: 'Cozy Suburban House',
    price: 450000,
    address: '456 Oak Rd, Suburbia, USA',
    bedrooms: 3,
    bathrooms: 2.5,
    description:
      'Charming family home with a large backyard and updated kitchen.',
    status: 'active',
    imageUrl: '/suburban-house.png',
    sqft: 1800,
    propertyType: 'Single Family',
  },
  {
    agentId: MOCK_AGENT_ID,
    title: 'Luxury Penthouse Suite',
    price: 1200000,
    address: '789 High Tower, Anytown, USA',
    bedrooms: 3,
    bathrooms: 3,
    description:
      'Exclusive penthouse with panoramic views and top-tier finishes.',
    status: 'pending',
    imageUrl: '/luxury-penthouse.png',
    sqft: 2500,
    propertyType: 'Penthouse',
  },
  {
    agentId: 'agent456',
    title: 'Rustic Countryside Cabin',
    price: 320000,
    address: '101 Forest Ln, Ruralville, USA',
    bedrooms: 2,
    bathrooms: 1,
    description: 'Quiet cabin perfect for getaways, surrounded by nature.',
    status: 'active',
    imageUrl: '/countryside-cabin.png',
    sqft: 900,
    propertyType: 'Cabin',
  },
  {
    agentId: MOCK_AGENT_ID,
    title: 'Beachfront Villa',
    price: 980000,
    address: '22 Ocean Dr, Beachtown, USA',
    bedrooms: 4,
    bathrooms: 3,
    description: 'Stunning villa with direct beach access and ocean views.',
    status: 'sold',
    imageUrl: '/beachfront-villa.png',
    sqft: 3000,
    propertyType: 'Villa',
  },
  {
    agentId: MOCK_AGENT_ID,
    title: 'Historic Victorian Mansion',
    price: 1850000,
    address: '55 Heritage Ave, Oldtown, USA',
    bedrooms: 6,
    bathrooms: 4.5,
    description:
      'Meticulously restored Victorian mansion with original hardwood floors and modern amenities.',
    status: 'active',
    imageUrl: '/large-estate-house.png',
    sqft: 4200,
    propertyType: 'Single Family',
  },
  {
    agentId: 'agent789',
    title: 'Modern Minimalist Condo',
    price: 680000,
    address: '301 Glass Tower, Metro City, USA',
    bedrooms: 2,
    bathrooms: 2,
    description:
      'Sleek minimalist design with floor-to-ceiling windows and smart home technology.',
    status: 'active',
    imageUrl: '/modern-living-room.png',
    sqft: 1100,
    propertyType: 'Condo',
  },
  {
    agentId: MOCK_AGENT_ID,
    title: 'Lakefront Retreat',
    price: 725000,
    address: '88 Waterside Dr, Laketown, USA',
    bedrooms: 3,
    bathrooms: 2.5,
    description:
      'Peaceful lakefront property with private dock and stunning sunset views.',
    status: 'active',
    imageUrl: '/modern-house-backyard.png',
    sqft: 2100,
    propertyType: 'Single Family',
  },
  {
    agentId: 'agent456',
    title: 'Urban Loft Conversion',
    price: 825000,
    address: '42 Industrial Blvd, Arts District, USA',
    bedrooms: 2,
    bathrooms: 1.5,
    description:
      'Converted warehouse loft with exposed brick, high ceilings, and artist studio space.',
    status: 'pending',
    imageUrl: '/modern-house-bedroom.png',
    sqft: 1600,
    propertyType: 'Loft',
  },
  {
    agentId: 'agent789',
    title: 'Mountain Chalet',
    price: 650000,
    address: '199 Alpine Way, Mountainview, USA',
    bedrooms: 4,
    bathrooms: 3,
    description:
      'Ski-in/ski-out chalet with stone fireplace and panoramic mountain views.',
    status: 'active',
    imageUrl: '/cozy-cottage.png',
    sqft: 2800,
    propertyType: 'Chalet',
  },
  {
    agentId: MOCK_AGENT_ID,
    title: 'Luxury Townhouse',
    price: 920000,
    address: '77 Brownstone Row, Uptown, USA',
    bedrooms: 4,
    bathrooms: 3.5,
    description:
      'Elegant townhouse with private garden, gourmet kitchen, and rooftop terrace.',
    status: 'active',
    imageUrl: '/luxury-suburban-home.png',
    sqft: 2600,
    propertyType: 'Townhouse',
  },
  {
    agentId: 'agent456',
    title: 'Desert Oasis Villa',
    price: 1100000,
    address: '333 Cactus Canyon Rd, Desert Springs, USA',
    bedrooms: 5,
    bathrooms: 4,
    description:
      'Southwestern-style villa with infinity pool, outdoor kitchen, and desert landscaping.',
    status: 'active',
    imageUrl: '/modern-house-exterior.png',
    sqft: 3400,
    propertyType: 'Villa',
  },
  {
    agentId: 'agent789',
    title: 'Cozy Cottage Duplex',
    price: 395000,
    address: '12 Maple Lane, Countryside, USA',
    bedrooms: 2,
    bathrooms: 1.5,
    description:
      'Charming duplex with separate entrances, perfect for rental income or multi-generational living.',
    status: 'active',
    imageUrl: '/modern-house-kitchen.png',
    sqft: 1400,
    propertyType: 'Duplex',
  },
  {
    agentId: MOCK_AGENT_ID,
    title: 'Waterfront Mansion',
    price: 2200000,
    address: '1 Harbor Point Estate, Coastal City, USA',
    bedrooms: 7,
    bathrooms: 6,
    description:
      'Grand waterfront estate with private beach, boat dock, and wine cellar.',
    status: 'pending',
    imageUrl: '/large-estate-house.png',
    sqft: 5500,
    propertyType: 'Single Family',
  },
  {
    agentId: 'agent456',
    title: 'Eco-Friendly Tiny Home',
    price: 185000,
    address: '404 Green Valley Rd, Sustainable Village, USA',
    bedrooms: 1,
    bathrooms: 1,
    description:
      'Solar-powered tiny home with composting toilet, rainwater collection, and organic garden.',
    status: 'active',
    imageUrl: '/cozy-cottage.png',
    sqft: 600,
    propertyType: 'Tiny Home',
  },
  {
    agentId: 'agent789',
    title: 'Metropolitan Studio Loft',
    price: 520000,
    address: '88 Metro Square, City Center, USA',
    bedrooms: 1,
    bathrooms: 1,
    description:
      'Open-concept studio with exposed beams and city skyline views.',
    status: 'active',
    imageUrl: '/downtown-apartment.png',
    sqft: 850,
    propertyType: 'Studio',
  },
  {
    agentId: MOCK_AGENT_ID,
    title: 'Family Ranch Estate',
    price: 675000,
    address: '256 Country Club Dr, Meadowbrook, USA',
    bedrooms: 4,
    bathrooms: 3,
    description: 'Sprawling ranch home with horse stables and 5-acre lot.',
    status: 'active',
    imageUrl: '/suburban-house.png',
    sqft: 2900,
    propertyType: 'Ranch',
  },
  {
    agentId: 'agent456',
    title: 'Executive Penthouse',
    price: 1650000,
    address: '500 Corporate Tower, Business District, USA',
    bedrooms: 4,
    bathrooms: 4,
    description:
      'Ultra-modern penthouse with private elevator and concierge service.',
    status: 'pending',
    imageUrl: '/luxury-penthouse.png',
    sqft: 3200,
    propertyType: 'Penthouse',
  },
  {
    agentId: 'agent789',
    title: 'Secluded Forest Cabin',
    price: 285000,
    address: '77 Pine Ridge Trail, Woodland, USA',
    bedrooms: 2,
    bathrooms: 1.5,
    description: 'Off-grid cabin with wood-burning stove and hiking trails.',
    status: 'active',
    imageUrl: '/countryside-cabin.png',
    sqft: 1050,
    propertyType: 'Cabin',
  },
  {
    agentId: MOCK_AGENT_ID,
    title: 'Oceanfront Paradise',
    price: 1450000,
    address: '12 Sunset Cove, Coastal Paradise, USA',
    bedrooms: 5,
    bathrooms: 4,
    description:
      'Luxury beachfront home with infinity pool and private cabana.',
    status: 'active',
    imageUrl: '/beachfront-villa.png',
    sqft: 3800,
    propertyType: 'Villa',
  },
  {
    agentId: 'agent456',
    title: 'Grand Victorian Estate',
    price: 2100000,
    address: '33 Victorian Gardens, Historic District, USA',
    bedrooms: 8,
    bathrooms: 6,
    description:
      'Magnificent Victorian mansion with turret, wraparound porch, and carriage house.',
    status: 'active',
    imageUrl: '/large-estate-house.png',
    sqft: 6200,
    propertyType: 'Single Family',
  },
  {
    agentId: 'agent789',
    title: 'Downtown High-Rise Condo',
    price: 780000,
    address: '99 Central Plaza, Downtown Core, USA',
    bedrooms: 2,
    bathrooms: 2.5,
    description:
      'High-floor condo with marble finishes and building amenities.',
    status: 'active',
    imageUrl: '/modern-living-room.png',
    sqft: 1350,
    propertyType: 'Condo',
  },
  {
    agentId: MOCK_AGENT_ID,
    title: 'Private Lake House',
    price: 890000,
    address: '44 Hidden Bay Dr, Crystal Lake, USA',
    bedrooms: 4,
    bathrooms: 3.5,
    description:
      'Secluded lakefront home with boathouse and entertainment deck.',
    status: 'sold',
    imageUrl: '/modern-house-backyard.png',
    sqft: 2700,
    propertyType: 'Single Family',
  },
  {
    agentId: 'agent456',
    title: 'Artist Quarter Loft',
    price: 695000,
    address: '155 Gallery Row, Arts Quarter, USA',
    bedrooms: 1,
    bathrooms: 2,
    description:
      'Converted artist loft with skylight, polished concrete floors, and gallery space.',
    status: 'active',
    imageUrl: '/modern-house-bedroom.png',
    sqft: 1800,
    propertyType: 'Loft',
  },
  {
    agentId: 'agent789',
    title: 'Alpine Ski Lodge',
    price: 1200000,
    address: '888 Powder Mountain Rd, Snow Valley, USA',
    bedrooms: 6,
    bathrooms: 4.5,
    description:
      'Luxury ski lodge with hot tub, game room, and mountain panorama.',
    status: 'active',
    imageUrl: '/cozy-cottage.png',
    sqft: 4100,
    propertyType: 'Chalet',
  },
  {
    agentId: MOCK_AGENT_ID,
    title: 'Upscale Brownstone',
    price: 1350000,
    address: '222 Heritage Row, Historic Uptown, USA',
    bedrooms: 5,
    bathrooms: 4,
    description:
      'Restored brownstone townhouse with original details and modern updates.',
    status: 'pending',
    imageUrl: '/luxury-suburban-home.png',
    sqft: 3100,
    propertyType: 'Townhouse',
  },
  {
    agentId: 'agent456',
    title: 'Southwest Desert Retreat',
    price: 950000,
    address: '777 Saguaro Vista, Desert Hills, USA',
    bedrooms: 4,
    bathrooms: 3.5,
    description:
      'Adobe-style home with casita, pool, and stunning desert views.',
    status: 'active',
    imageUrl: '/modern-house-exterior.png',
    sqft: 2800,
    propertyType: 'Villa',
  },
  {
    agentId: 'agent789',
    title: 'Income Property Duplex',
    price: 485000,
    address: '66 Investment Ave, Rental District, USA',
    bedrooms: 4,
    bathrooms: 3,
    description:
      'Well-maintained duplex with solid rental history and separate utilities.',
    status: 'active',
    imageUrl: '/modern-house-kitchen.png',
    sqft: 2200,
    propertyType: 'Duplex',
  },
  {
    agentId: MOCK_AGENT_ID,
    title: 'Bayfront Mega Mansion',
    price: 3500000,
    address: '1 Billionaire Bay, Elite Shores, USA',
    bedrooms: 9,
    bathrooms: 8,
    description:
      'Ultra-luxury waterfront estate with tennis court, helicopter pad, and staff quarters.',
    status: 'active',
    imageUrl: '/large-estate-house.png',
    sqft: 8500,
    propertyType: 'Single Family',
  },
  {
    agentId: 'agent456',
    title: 'Minimalist Tiny House',
    price: 225000,
    address: '555 Simple Living Ln, Tiny Village, USA',
    bedrooms: 1,
    bathrooms: 1,
    description:
      'Modern tiny house with murphy bed, compact kitchen, and outdoor living space.',
    status: 'active',
    imageUrl: '/cozy-cottage.png',
    sqft: 400,
    propertyType: 'Tiny Home',
  },
  {
    agentId: 'agent789',
    title: 'City View Apartment',
    price: 645000,
    address: '321 Skyline Blvd, Midtown, USA',
    bedrooms: 2,
    bathrooms: 2,
    description:
      'Modern apartment with panoramic city views and building gym access.',
    status: 'active',
    imageUrl: '/downtown-apartment.png',
    sqft: 1150,
    propertyType: 'Apartment',
  },
  {
    agentId: MOCK_AGENT_ID,
    title: 'Country Manor House',
    price: 825000,
    address: '99 Rolling Hills Dr, Countryside Estates, USA',
    bedrooms: 5,
    bathrooms: 4,
    description:
      'Colonial-style manor with circular driveway, pool, and guest cottage.',
    status: 'active',
    imageUrl: '/suburban-house.png',
    sqft: 3600,
    propertyType: 'Single Family',
  },
  {
    agentId: 'agent456',
    title: 'Sky Tower Penthouse',
    price: 2800000,
    address: '1000 Cloud Nine Tower, Sky District, USA',
    bedrooms: 5,
    bathrooms: 5.5,
    description:
      'Top-floor penthouse with 360-degree views, wine cellar, and private terrace.',
    status: 'active',
    imageUrl: '/luxury-penthouse.png',
    sqft: 4500,
    propertyType: 'Penthouse',
  },
  {
    agentId: 'agent789',
    title: 'Mountain Hideaway Cabin',
    price: 365000,
    address: '123 Bear Creek Rd, Mountain Refuge, USA',
    bedrooms: 3,
    bathrooms: 2,
    description:
      'Rustic log cabin with creek frontage, fire pit, and wildlife viewing.',
    status: 'sold',
    imageUrl: '/countryside-cabin.png',
    sqft: 1650,
    propertyType: 'Cabin',
  },
  {
    agentId: MOCK_AGENT_ID,
    title: 'Tropical Beach Villa',
    price: 1750000,
    address: '7 Paradise Point, Tropical Coast, USA',
    bedrooms: 6,
    bathrooms: 5,
    description:
      'Mediterranean-style villa with palm trees, outdoor kitchen, and beach access.',
    status: 'pending',
    imageUrl: '/beachfront-villa.png',
    sqft: 4200,
    propertyType: 'Villa',
  },
  {
    agentId: 'agent456',
    title: 'Heritage Victorian Home',
    price: 1550000,
    address: '444 Antique Ave, Heritage Hills, USA',
    bedrooms: 7,
    bathrooms: 5,
    description:
      'Authentic Victorian home with period fixtures, bay windows, and rose garden.',
    status: 'active',
    imageUrl: '/large-estate-house.png',
    sqft: 4800,
    propertyType: 'Single Family',
  },
  {
    agentId: 'agent789',
    title: 'Glass Tower Residence',
    price: 920000,
    address: '777 Crystal Tower, Financial District, USA',
    bedrooms: 3,
    bathrooms: 2.5,
    description:
      'Ultra-modern condo with floor-to-ceiling windows and smart home integration.',
    status: 'active',
    imageUrl: '/modern-living-room.png',
    sqft: 1650,
    propertyType: 'Condo',
  },
  {
    agentId: MOCK_AGENT_ID,
    title: 'Secluded Lake Cabin',
    price: 615000,
    address: '321 Quiet Cove Rd, Peaceful Lake, USA',
    bedrooms: 3,
    bathrooms: 2,
    description:
      'Charming lake cabin with fishing dock, screened porch, and fire pit.',
    status: 'active',
    imageUrl: '/modern-house-backyard.png',
    sqft: 1900,
    propertyType: 'Cabin',
  },
  {
    agentId: 'agent456',
    title: 'Industrial Loft Space',
    price: 750000,
    address: '88 Factory Row, Industrial Park, USA',
    bedrooms: 2,
    bathrooms: 2,
    description:
      'Raw loft space with exposed pipes, concrete floors, and artist studio potential.',
    status: 'active',
    imageUrl: '/modern-house-bedroom.png',
    sqft: 2100,
    propertyType: 'Loft',
  },
  {
    agentId: 'agent789',
    title: 'Snow Peak Chalet',
    price: 875000,
    address: '999 Summit Ridge, Alpine Heights, USA',
    bedrooms: 5,
    bathrooms: 3.5,
    description:
      'Wooden chalet with vaulted ceilings, stone fireplace, and ski storage.',
    status: 'active',
    imageUrl: '/cozy-cottage.png',
    sqft: 3300,
    propertyType: 'Chalet',
  },
  {
    agentId: MOCK_AGENT_ID,
    title: 'Historic Townhouse Row',
    price: 1150000,
    address: '555 Colonial Court, Old Town, USA',
    bedrooms: 4,
    bathrooms: 3.5,
    description:
      'Historic townhouse with brick facade, courtyard garden, and period details.',
    status: 'active',
    imageUrl: '/luxury-suburban-home.png',
    sqft: 2400,
    propertyType: 'Townhouse',
  },
  {
    agentId: 'agent456',
    title: 'Desert Oasis Estate',
    price: 1325000,
    address: '111 Mirage Dr, Desert Oasis, USA',
    bedrooms: 6,
    bathrooms: 4.5,
    description:
      'Sprawling desert estate with multiple pools, tennis court, and guest house.',
    status: 'sold',
    imageUrl: '/modern-house-exterior.png',
    sqft: 4600,
    propertyType: 'Villa',
  },
  {
    agentId: 'agent789',
    title: 'Twin Home Duplex',
    price: 535000,
    address: '234 Twin Oaks Dr, Family Neighborhood, USA',
    bedrooms: 3,
    bathrooms: 2.5,
    description:
      'Modern duplex with shared driveway, fenced yards, and energy-efficient appliances.',
    status: 'active',
    imageUrl: '/modern-house-kitchen.png',
    sqft: 1800,
    propertyType: 'Duplex',
  },
  {
    agentId: MOCK_AGENT_ID,
    title: 'Exclusive Waterfront Estate',
    price: 4200000,
    address: '2 Platinum Point, Exclusive Bay, USA',
    bedrooms: 10,
    bathrooms: 9,
    description:
      'Premier waterfront estate with private marina, infinity pool, and wine cave.',
    status: 'active',
    imageUrl: '/large-estate-house.png',
    sqft: 12000,
    propertyType: 'Single Family',
  },
  {
    agentId: 'agent456',
    title: 'Off-Grid Tiny Retreat',
    price: 195000,
    address: '888 Freedom Trail, Off-Grid Community, USA',
    bedrooms: 1,
    bathrooms: 1,
    description:
      'Self-sufficient tiny home with solar panels, composting system, and herb garden.',
    status: 'active',
    imageUrl: '/cozy-cottage.png',
    sqft: 500,
    propertyType: 'Tiny Home',
  },
  {
    agentId: 'agent789',
    title: 'Corporate Apartment Suite',
    price: 695000,
    address: '600 Executive Plaza, Corporate Center, USA',
    bedrooms: 2,
    bathrooms: 2,
    description:
      'Furnished corporate apartment with concierge, fitness center, and meeting rooms.',
    status: 'pending',
    imageUrl: '/downtown-apartment.png',
    sqft: 1250,
    propertyType: 'Apartment',
  },
  {
    agentId: MOCK_AGENT_ID,
    title: 'Suburban Dream Home',
    price: 565000,
    address: '777 Apple Tree Lane, Suburbia Heights, USA',
    bedrooms: 4,
    bathrooms: 2.5,
    description:
      'Perfect family home with two-car garage, finished basement, and playground nearby.',
    status: 'active',
    imageUrl: '/suburban-house.png',
    sqft: 2200,
    propertyType: 'Single Family',
  },
  {
    agentId: 'agent456',
    title: 'Luxury Sky Penthouse',
    price: 3200000,
    address: '5000 Cloud Tower, Elite Heights, USA',
    bedrooms: 6,
    bathrooms: 6,
    description:
      'Ultra-luxury penthouse with helicopter access, butler service, and city panorama.',
    status: 'active',
    imageUrl: '/luxury-penthouse.png',
    sqft: 5200,
    propertyType: 'Penthouse',
  },
  {
    agentId: 'agent789',
    title: 'Wilderness Log Cabin',
    price: 295000,
    address: '444 Deer Path, Wilderness Reserve, USA',
    bedrooms: 2,
    bathrooms: 1,
    description:
      'Authentic log cabin with wood stove, well water, and 20 acres of forest.',
    status: 'active',
    imageUrl: '/countryside-cabin.png',
    sqft: 1100,
    propertyType: 'Cabin',
  },
];
